#!/bin/bash
./test_cg.sh
#./test_anm.sh
./test_anm_wrapper.sh
#./test_eigen_vectors.sh
./test_eigen_vectors_wrapper.sh
./test_msf.sh
./test_conformation.sh
./test_trajectory.sh
./test_internal_pca.sh
./test_pca.sh
./test_mds.sh
./test_tsne.sh
